### ISSUE TITLE
Silk Moth should be able to breed just like Bees [Suggestion] 

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#103]
### Description

Bees can be bred with flowers, I think the same should apply with silk moth, this is useful especially for silk farms.

**Comment by OpenBagTwo** [comment]
PSA--and I have literally just confirmed this--**Silk moths are breedable** in the current version of the game.

Because [`SilkMothEntity implements DespawnableAnimal`](https://github.com/quiqueck/BetterEnd/blob/a5bfe04ed1c239f2c0765face7e16319b8414a3c/src/main/java/org/betterx/betterend/entity/SilkMothEntity.java#L49) and [`DespawnableAnimal` is an extremely minimal abstract class that `extends Animal`](https://github.com/quiqueck/BCLib/blob/41b1d9eb68e7e8579f15a39566e39caf7fad665d/src/main/java/org/betterx/bclib/entity/DespawnableAnimal.java#L7), `SilkMothEntity` inherits the default behavior from the `Animal` abstract class where, explicity:

 ```java
  // I prefer the Yarn mapping which calls this method isBreedingItem
  public boolean isFood(ItemStack itemStack) {
    return itemStack.is(Items.WHEAT);
  }
```
That is, **if you want baby silk moths, feed 'em wheat!**

![2022-10-30_12 40 23](https://user-images.githubusercontent.com/66568922/198890815-d3f59484-2bcf-496e-b6a2-48786ee67ad5.png)
![2022-10-30_12 37 30](https://user-images.githubusercontent.com/66568922/198890814-1f930108-a4dd-4dd5-be57-d1de1f0bc78a.png)

Just make sure to name them, [as otherwise](https://github.com/quiqueck/BCLib/blob/41b1d9eb68e7e8579f15a39566e39caf7fad665d/src/main/java/org/betterx/bclib/entity/DespawnableAnimal.java#L12-L15):
> ```java
>  @Override
>     public boolean removeWhenFarAway(double d) {
>         return !this.hasCustomName();
>     }
> ```

**Comment by ChristopherJ123** [comment]
Thanks for the info!😊 This will help alot!

But still it doesn't make sense to feed them with wheat, maybe using betterend plants is more accurate. Also, the despawn when far away without name tag could be improved to work similarly with bees, they shouldn't despawn.

**Comment by OpenBagTwo** [comment]
@ChristopherJ123 see my PR (#109). I believe making a silk moth farm right now would be an exercise in futility, given that un-named moths despawn (and named ones *might* lose their names on saving / loading).

I'd love your input on the changes I've proposed, especially regarding what item or items can put a moth into "love mode."

**Comment by ChristopherJ123** [comment]
Oh woww nice!! I will look it up tomorrow😃

**Comment by ChristopherJ123** [comment]
> I'd love your input on the changes I've proposed, especially regarding what item or items can put a moth into "love mode."

Perhaps blossom berry could be a potential breeding item, considering it has a flower and similarly how bees are attracted to flowers, also they are in the same biome with silk moths. Blossom berry seeds could also be a choice. What do oyu think🙂

![2022-10-31_18 03 19](https://user-images.githubusercontent.com/86960084/198994703-fa02d78b-d944-471e-9d77-9827680c1174.png)

**Comment by OpenBagTwo** [comment]
I love that idea.

**Comment by quiqueck** [comment]
Thanks again for the PR. I just changed some minor details. Mainly that the food item is a blossom berry and that the moths will follow players holding a blossom berry (otherwise I found it quite hard to give them the food :D )

**Comment by ChristopherJ123** [comment]
Thanks for the hardwork yall :D Appreciated it
