### ISSUE TITLE
Just crashing me in general still

### ISSUE THREAD

**Issue by Loh-key** [quiqueck/BetterEnd#36]
### What happened?

Ok I opened a bug which you rightly closed upon realizing I had some outdated/conflicting versions of things.  I'm on the newest version of BetterEnd, BetterNether and BClib, and my game is just hating it.  I remove those 3 from my mod folder? everything is fine.  So it's something in one of those 3 either conflicting with one of my other mods, or just not working at all.
[latest.log](https://github.com/quiqueck/BetterEnd/files/9082563/latest.log)
 

### BetterEnd

2.02

### BCLib

2.0.10

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by Loh-key** [comment]
log attached to original comment

**Comment by quiqueck** [comment]
While the log does not mention BetterEnd directly, it may be an issue with our armor mixing. The issue is almost certainly a compatibility issue, as I can not reproduce this behavior. But  I just improved the code such that it will be more resilient towards misconfigured armor.

#33 might also be caused by the same faulty mixin state.

**Comment by Loh-key** [comment]
So is there anything I can do in the meantime? I'd really like to use BetterEnd, but not at the expense of all my other mods.  Maybe if you can help me pinpoint wherein the error lies, I can make the decision over one or the other?

**Comment by quiqueck** [comment]
It is related to the Armor Rendering. So any other mod that changes the behavior of default armor (a potential candidate could be Armored Elytras) might trigger that crash.

Since you are migrating an existing world, it may also not be related to missing armor models (that for example are attached to armor stands). So you could try to remove those armor parts from the players as well as any armor stand before upgrading.

**Comment by Loh-key** [comment]
![screenshot 668](https://user-images.githubusercontent.com/108998919/178351554-f2ffb38f-a201-4df5-be42-acf5fd14f3f9.png)
this means nada to me (can't code) but MrMelon is the author of the *mod* ArmoredElytra, whereas the datapack ArmoredElytra is from VanillaTweaks and will be removed now that Colytra is in 1.19*.  

In short TL;DR yeah the mod version of Armored Elytra is a cosmetic mod that renders an elytra and chestplate on player body.  Are you 100% sure it's armor? I do have armor stands decorating things that I can go destroy to test that.  I can also remove armored elytra and load with your mods and see if that solves.

**Comment by quiqueck** [comment]
Well, the method from the crash log is related to Armor rendering. Since I am not able to reproduce the crash, I cant't be 100% sure. But that armor is my first guess (and the section of code that I did improve to try and fix this issue).

Rendering is all about the cosmetics of the armor, so the ArmoredElytra-Mod is probably also hooked into the same methods as our armor code. I would first disable armored elytra and try again (if it runs we know that it is a compatibility issue with that mod). If it doesn't there might be armor items in game that were not converted the way we would need the too. So the second option is to remove all armor related items from the world and try again.

**Comment by Loh-key** [comment]
Sounds good, I'll back up a save and start with removing ArmoredElytra.

**Comment by quiqueck** [comment]
I am preparing the next update right now. Should be available on CurseFore in a few minutes.

**Comment by Loh-key** [comment]
Ok, it WORKED BOTH NETHER AND END WITH ONLY REMOVING ARMOREDELYTRA (MOD: https://www.curseforge.com/minecraft/mc-mods/armored-elytra/files) please excuse the caps but I am incredibly excited.  I've been trying to get BetterEnd to work ever since that Aphid mount mod got released... seriously.  This is my first time modding minecraft in nearly 10 years of playing (lol) and this first big issue that I couldn't resolve on my own; you were really kind and patient with me and I appreciate that immensely. 

I will now try downloading the new update and seeing if it meshes with ArmoredElytra.  If not, I will abandon it, it's a minor cosmetic mod.  I will close with comment regardless of if they work together or not (and inform you)

**Comment by quiqueck** [comment]
Glad it did work :)
And the new release may also restore compatibility with armored elytra.

**Comment by Loh-key** [comment]
You know how a lot of human origin stories are full of "magic" and otherworldly things, but things that we now understand as just basic nature? Yeah I am the caveman staring in wonder at the magic of fire :P

![image](https://user-images.githubusercontent.com/108998919/178362383-2ab58141-488e-4735-943f-a1b217d8c0fa.png)
just me and my boys about to go end busting with our armored elytra... and excited about going into the end for the first time in years.  Seriously, thanks so much!! 

I know screenshot doesn't show biomes, hopefully skybox is enough to prove to you it's working lol.  I legit have not played this world other than to set up mods.  In over my head but enjoying the ride haha.  Have a great day/night/week

**Comment by mrmelon54** [comment]
hey I was looking through my issues and found you mentioned that issue
did you get that compatibility working in the end?

**Comment by Loh-key** [comment]
yes!
